# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalonol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(default='新玩家', max_length=16),
            preserve_default=False,
        ),
    ]
